// generated by stringer -type=altitudeModeEnum; DO NOT EDIT

package kml

import "fmt"

const _altitudeModeEnum_name = "clampToGroundrelativeToGroundabsolute"

var _altitudeModeEnum_index = [...]uint8{0, 13, 29, 37}

func (i altitudeModeEnum) String() string {
	if i < 0 || i+1 >= altitudeModeEnum(len(_altitudeModeEnum_index)) {
		return fmt.Sprintf("altitudeModeEnum(%d)", i)
	}
	return _altitudeModeEnum_name[_altitudeModeEnum_index[i]:_altitudeModeEnum_index[i+1]]
}
