// generated by stringer -type=colorModeEnum; DO NOT EDIT

package kml

import "fmt"

const _colorModeEnum_name = "normalrandom"

var _colorModeEnum_index = [...]uint8{0, 6, 12}

func (i colorModeEnum) String() string {
	if i < 0 || i+1 >= colorModeEnum(len(_colorModeEnum_index)) {
		return fmt.Sprintf("colorModeEnum(%d)", i)
	}
	return _colorModeEnum_name[_colorModeEnum_index[i]:_colorModeEnum_index[i+1]]
}
