// generated by stringer -type=gridOriginEnum; DO NOT EDIT

package kml

import "fmt"

const _gridOriginEnum_name = "LowerLeftUpperLeft"

var _gridOriginEnum_index = [...]uint8{0, 9, 18}

func (i gridOriginEnum) String() string {
	if i < 0 || i+1 >= gridOriginEnum(len(_gridOriginEnum_index)) {
		return fmt.Sprintf("gridOriginEnum(%d)", i)
	}
	return _gridOriginEnum_name[_gridOriginEnum_index[i]:_gridOriginEnum_index[i+1]]
}
