// generated by stringer -type=refreshModeEnum; DO NOT EDIT

package kml

import "fmt"

const _refreshModeEnum_name = "onChangeonIntervalonExpire"

var _refreshModeEnum_index = [...]uint8{0, 8, 18, 26}

func (i refreshModeEnum) String() string {
	if i < 0 || i+1 >= refreshModeEnum(len(_refreshModeEnum_index)) {
		return fmt.Sprintf("refreshModeEnum(%d)", i)
	}
	return _refreshModeEnum_name[_refreshModeEnum_index[i]:_refreshModeEnum_index[i+1]]
}
